Hub-737: Tear down short-hub abtest and keep the variant
alphagov/verify-frontend pull request #906
Opened 2020-11-13 17:39 UTC by jkunle

**What**
We need to remove the short hub AB test and keep the variant.
https://govukverify.atlassian.net/browse/HUB-737
see: https://github.com/alphagov/verify-frontend-federation-config/pull/184
see: https://github.com/alphagov/verify-acceptance-tests/pull/106

**Why**

The variant won! We've set it to 100% so all users are seeing it, but now we need to do the cleanup.

**Description**
Current control artefacts i.e. controllers, views was renamed, the variant is then re-named to the control, the Controllers and views that are associated with the **long hub journey**  below has been removed in favour of the short-hub journey.
This is easier to review commit by commit

![image](https://user-images.githubusercontent.com/3749690/99103044-dc0cfd80-25d6-11eb-9e90-92087ea7164d.png)

![image](https://user-images.githubusercontent.com/3749690/99099244-132ce000-25d2-11eb-9401-587d51574a9f.png)

The Redirect to warning controller  below has been removed

![image](https://user-images.githubusercontent.com/3749690/99103156-0bbc0580-25d7-11eb-9ddb-d127ebbd9b92.png)

Throttling functionality has been remove, there may still be some artefacts of it left in the config

The about pages ie. the educational pages for the LOA1 now uses the short-hub combined about page,
and now use single controller and view.

The old idp rules have been removed in favour of the short idp rules.

All traces of ABTest experiments have been removed from controller specs

2020-11-16 12:48 UTC, Wynndow commented on spec/models/select_documents_form_spec.rb
> -require "spec_helper"
Deleting this spec file means that `app/models/select_documents_form.rb` now doesn't have any tests. I know the model is simpler but could you add something to cover it?

2020-11-16 12:50 UTC, Wynndow commented on app/constraints/select_route.rb
> +private
`cookie_matches_experiment?` only seems to be used in this  class, so could stay private?

2020-11-16 12:50 UTC, Wynndow commented on app/constraints/select_route.rb
> +private
`cookie_matches_experiment?` only seems to be used in this  class, so could stay private?

2020-11-16 12:51 UTC, Wynndow commented on config/locales/cy.yml
> +      cannot_verify: What to do if you cannot use GOV.UK Verify
This content seems to have become English - should probably stay as Welsh

2020-11-16 12:52 UTC, Wynndow requested changes
I don't have much experience with the AB stuff but the changes seem fine as far as I can tell. Only a few comments on some minor stuff - the translation stuff should probably be fixed up though.

2020-11-17 08:04 UTC, jkunle commented on spec/models/select_documents_form_spec.rb
> -require "spec_helper"
Thanks

2020-11-17 08:05 UTC, jkunle commented on config/locales/cy.yml
> +      cannot_verify: What to do if you cannot use GOV.UK Verify
Many thanks for spotting this

2020-11-17 15:01 UTC, Wynndow approved these changes

2020-11-18 10:01 UTC, JohnWattsGDS approved these changes

2020-11-18 16:07 UTC, merged